version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ordersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1skp8gr29jnoj"
s3_prefix = "ordersapi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
